FROM rocker/tidyverse

RUN apt-get update && apt-get install -y git-core imagemagick libboost-dev libcairo2-dev libcurl4-openssl-dev libgit2-dev libicu-dev libmagic-dev libmagick++-dev libpng-dev libssl-dev libxml2-dev make pandoc pandoc-citeproc qpdf zlib1g-dev

RUN apt-get install -y gdebi-core wget
RUN wget https://download3.rstudio.org/ubuntu-14.04/x86_64/shiny-server-1.5.16.958-amd64.deb
RUN gdebi -n shiny-server-1.5.16.958-amd64.deb

RUN echo "options(repos = c(CRAN = 'https://cran.rstudio.com/'), download.file.method = 'libcurl', Ncpus = 4)" >> /usr/local/lib/R/etc/Rprofile.site
RUN R -e 'install.packages("remotes")'
RUN Rscript -e 'remotes::install_version("rlang",upgrade="never", version = "0.4.11")'
RUN Rscript -e 'remotes::install_version("tibble",upgrade="never", version = "3.1.1")'
RUN Rscript -e 'remotes::install_version("png",upgrade="never", version = "0.1-7")'
RUN Rscript -e 'remotes::install_version("R6",upgrade="never", version = "2.5.0")'
RUN Rscript -e 'remotes::install_version("curl",upgrade="never", version = "4.3.2")'
RUN Rscript -e 'remotes::install_version("base64enc",upgrade="never", version = "0.1-3")'
RUN Rscript -e 'remotes::install_version("purrr",upgrade="never", version = "0.3.4")'
RUN Rscript -e 'remotes::install_version("stringr",upgrade="never", version = "1.4.0")'
RUN Rscript -e 'remotes::install_version("Rcpp",upgrade="never", version = "1.0.7")'
RUN Rscript -e 'remotes::install_version("knitr",upgrade="never", version = "1.33")'
RUN Rscript -e 'remotes::install_version("testthat",upgrade="never", version = "3.0.2")'
RUN Rscript -e 'remotes::install_version("shiny",upgrade="never", version = "1.6.0")'
RUN Rscript -e 'remotes::install_version("config",upgrade="never", version = "0.3.1")'
RUN Rscript -e 'remotes::install_version("styler",upgrade="never", version = "1.6.2")'
RUN Rscript -e 'remotes::install_version("shinytest",upgrade="never", version = "1.5.0")'
RUN Rscript -e 'remotes::install_version("rmarkdown",upgrade="never", version = "2.11")'
RUN Rscript -e 'remotes::install_version("magick",upgrade="never", version = "2.7.3")'
RUN Rscript -e 'remotes::install_version("lintr",upgrade="never", version = "2.0.1")'
RUN Rscript -e 'remotes::install_version("dplyr",upgrade="never", version = "1.0.7")'
RUN Rscript -e 'remotes::install_version("covr",upgrade="never", version = "3.5.1")'
RUN Rscript -e 'remotes::install_version("devtools",upgrade="never", version = "2.4.3")'
RUN Rscript -e 'remotes::install_version("spelling",upgrade="never", version = "2.2")'
RUN Rscript -e 'remotes::install_version("shinyjs",upgrade="never", version = "2.0.0")'
RUN Rscript -e 'remotes::install_version("gargoyle",upgrade="never", version = "0.0.1")'
RUN Rscript -e 'remotes::install_version("readr",upgrade="never", version = "2.1.0")'
RUN Rscript -e 'remotes::install_version("ggplot2",upgrade="never", version = "3.3.4")'
RUN Rscript -e 'remotes::install_version("BH",upgrade="never", version = "1.75.0-0")'
RUN Rscript -e 'remotes::install_version("globals",upgrade="never", version = "0.14.0")'
RUN Rscript -e 'remotes::install_version("golem",upgrade="never", version = "0.3.1")'

RUN Rscript -e 'install.packages("cloc", repos = c("https://cinc.rud.is", "https://cloud.r-project.org/"))'
RUN wget https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-linux-x86_64.tar.bz2
RUN tar xvf phantomjs-2.1.1-linux-x86_64.tar.bz2
RUN mv phantomjs-2.1.1-linux-x86_64 /opt
RUN ln -s /opt/phantomjs-2.1.1-linux-x86_64/bin/phantomjs /usr/local/bin/

RUN mkdir /build_zone
ADD . /build_zone
WORKDIR /build_zone
RUN R -e 'remotes::install_local(upgrade="never")'
RUN rm -rf /build_zone

ARG SHINY_APP_DIR=/srv/shiny-server/nbinomPlot
ARG SHINY_APP="${SHINY_APP_DIR}/app.R"
RUN mkdir -p "${SHINY_APP_DIR}"

ARG R_USERNAME=rstudio
ARG R_USER_GROUP_NAME="${R_USERNAME}:${R_USERNAME}"
RUN echo "Sys.setlocale('LC_ALL','en_US.UTF-8');Sys.setenv(LANG='en_US.UTF-8');" >> /etc/R/Rprofile.site
RUN echo "Sys.setlocale('LC_ALL','en_US.UTF-8');Sys.setenv(LANG='en_US.UTF-8');" >> "/home/${R_USERNAME}/.Rprofile"
RUN chown "${R_USER_GROUP_NAME}" "/home/${R_USERNAME}/.Rprofile"
RUN echo "nbinomPlot::run_app()" >> "${SHINY_APP}"

# Run Shiny Server by sudoers
RUN usermod -aG sudo "${R_USERNAME}"

EXPOSE 3838
EXPOSE 8787
