# For help debugging build failures open an issue on the RStudio community with the 'github-actions' tag.
# https://community.rstudio.com/new-topic?category=Package%20development&tags=github-actions
on:
  push:
    branches:
      - main
      - master
      - cmake
  pull_request:
    branches:
      - main
      - master

name: R-CMD-check

jobs:
  R-CMD-check:
    runs-on: ubuntu-20.04
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_HOME: /opt/R/3.6.3/lib/R
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-pandoc@v1
      - uses: r-lib/actions/setup-r@v1
        with:
          r-version: 3.6.3

      - name: Install R package dependencies
        run: |
          sudo apt-get install -y cmake git-core imagemagick libboost-dev libcairo2-dev libcurl4-openssl-dev libgit2-dev libicu-dev libmagic-dev libmagick++-dev libpng-dev libssl-dev libxml2-dev make pandoc pandoc-citeproc qpdf zlib1g-dev
          mkdir -p ./tests/build

      - name: Setup Rcpp
        run: |
          install.packages(c("Rcpp", "BH"))
        shell: Rscript {0}

      - name: Check cmake
        working-directory: ./tests/build
        run: |
          cmake ..
          make
          make test

      - name: Install dependencies
        run: |
          install.packages(c("remotes", "rcmdcheck"))
          remotes::install_deps(dependencies = TRUE)
        shell: Rscript {0}

      - name: Install this package
        run: |
          R CMD build .
          R CMD INSTALL nbinomPlot_0.0.0.9000.tar.gz
          R CMD check --no-manual --no-tests nbinomPlot_0.0.0.9000.tar.gz

      - name: Testing
        run: |
          Rscript -e 'library(devtools); devtools::test(); Sys.setlocale("LC_MESSAGES", "en_US.UTF-8"); Sys.setlocale("LC_COLLATE", "en_US.UTF-8"); Sys.setenv(LANG = "en_US.UTF-8"); devtools::test()'
